# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4b446671066c95a9eef542ddddbba2d36827cbff1da5269163cb567e2daea6ad11abf57ebee8a2d2c06c59146a29333ad57a455cf41159b4f2d916dcca96ca0

test:
  secret_key_base: b04fad1e1559c8ca0efc678482b1753e391d3f38b2f9bdc9b91caafd7c5fa2c633fa1b88a2bee430ce0d231fcf1b56d69bc9f883d83069713fa29a325e483f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
